import type { CpuMiningConfig, CpuProfile, NormalizedError, SafetyCondition } from './types.js';
export function detectSafetyConditions(input: { profile: CpuProfile; config: CpuMiningConfig; contentionReasons?: string[]; adapterHealth?: { status: string; reasons: string[] }; adapterError?: NormalizedError; at: string }): SafetyCondition[] {
  const conditions: SafetyCondition[] = []; const { profile, config, at } = input; const thermalLimit = config.resourceLimits?.maximumTemperatureCelsius ?? profile.thermalState.criticalThresholdCelsius ?? profile.thermalState.warningThresholdCelsius;
  if ((thermalLimit !== undefined && (profile.thermalState.currentCelsius ?? -Infinity) > thermalLimit) || ['warning', 'critical'].includes(profile.thermalState.state)) conditions.push(condition('excessive-cpu-temperature', profile.thermalState.state === 'critical' ? 'critical' : 'warning', at, 'CPU thermal provider reports a temperature/state beyond the configured or provider threshold.', { thermal: profile.thermalState, thermalLimit }));
  const powerLimit = config.resourceLimits?.maximumPowerWatts ?? profile.powerState.budgetLimitWatts ?? profile.powerState.maximumRatedWatts;
  if (profile.powerState.budgetExceeded || (powerLimit !== undefined && (profile.powerState.currentWatts ?? -Infinity) > powerLimit)) conditions.push(condition('excessive-cpu-power', 'warning', at, 'CPU power provider reports a budget breach or power above the applicable limit.', { power: profile.powerState, powerLimit }));
  if ((input.contentionReasons?.length ?? 0) > 0) conditions.push(condition('resource-contention', 'warning', at, 'IRIA-shaped provider reports CPU resource contention.', { reasons: input.contentionReasons }));
  if (profile.hardwareHealth !== 'healthy') conditions.push(condition('hardware-health-degradation', profile.hardwareHealth === 'faulted' ? 'critical' : 'warning', at, 'IHIS-shaped provider reports degraded CPU health.', { health: profile.hardwareHealth, reasons: profile.hardwareHealthReasons }));
  if (input.adapterHealth?.status === 'faulted' || input.adapterError?.category === 'ProcessFailure') conditions.push(condition('miner-crash', 'critical', at, 'Adapter reports a faulted backend or normalized process failure.', { health: input.adapterHealth, error: input.adapterError }));
  if (input.adapterError?.category === 'PoolFailure' || input.adapterError?.category === 'NetworkFailure' || input.adapterHealth?.reasons.some((reason) => /pool/i.test(reason))) conditions.push(condition('pool-failure', 'warning', at, 'Adapter health/error indicates a pool connectivity failure.', { health: input.adapterHealth, error: input.adapterError }));
  const invalid = !config.walletReference.trim() || !config.workerIdentity.trim() || !config.pool.endpoint.trim() || config.threadAllocation.requestedThreads <= 0;
  if (invalid) conditions.push(condition('invalid-configuration', 'error', at, 'CPU mining configuration is missing a required opaque reference, identity, endpoint, or positive thread request.', {}));
  return conditions;
}
function condition(type: SafetyCondition['type'], severity: SafetyCondition['severity'], detectedAt: string, rationale: string, evidence: Record<string, unknown>): SafetyCondition { return Object.freeze({ type, severity, detectedAt, rationale, evidence: Object.freeze(evidence) }); }
