import { describe, expect, it } from 'vitest';
import { MinerProcessManager } from '../src/MinerProcessManager.js';
import { MINER_PROCESS_EVENTS } from '../src/events.js';
import { ProcessLifecycleStage } from '../src/types.js';
import { deterministicBackoff } from '../src/restart.js';
import { deps, request } from './testHelpers.js';
describe('Institutional Miner Process Manager', () => {
 it('runs the explicit lifecycle, immutable identity, ordered resource gate, graph, events, and redacted output', async () => { const d=deps(); const m=new MinerProcessManager(d); const received:string[]=[]; for(const e of Object.values(MINER_PROCESS_EVENTS))m.events.subscribe(e,()=>received.push(e)); const p=await m.launch(request({args:['--token','secret-ref']})); expect(p.lifecycle.map(x=>x.to)).toEqual([ProcessLifecycleStage.Requested,ProcessLifecycleStage.Validated,ProcessLifecycleStage.Prepared,ProcessLifecycleStage.Spawned,ProcessLifecycleStage.Starting,ProcessLifecycleStage.Running]); expect(d.calls).toEqual(['availability','reservation','permission']); expect(Object.isFrozen(p.identity)).toBe(true); expect(p.identity?.commandIdentity.args.join(' ')).not.toContain('ultra-secret'); m.capture(p.processUuid,'workload-1','stdout','hello ultra-secret'); expect(JSON.stringify(d.logs)).not.toContain('ultra-secret'); expect(m.graph.traceResource('gpu-01')[0]).toMatchObject({pluginUuid:'plugin-1',workloadUuid:'workload-1',adapterUuid:'adapter-1',processUuid:p.processUuid}); await m.stop(p.processUuid,'workload-1'); await m.terminate(p.processUuid,'workload-1'); expect(received).toContain(MINER_PROCESS_EVENTS.MinerProcessTerminated); });
 it('rejects duplicate, cross-process control, shell-shaped arguments, paths, environment passthrough, and executable substitution', async () => { const d=deps(); const m=new MinerProcessManager(d); const p=await m.launch(request()); await expect(m.launch(request())).rejects.toThrow('already active'); await expect(m.stop(p.processUuid,'other')).rejects.toThrow('scope violation'); await expect(m.launch(request({parentWorkloadUuid:'w2',adapterUuid:'a2',args:['; rm -rf /']}))).rejects.toThrow('shell'); await expect(m.launch(request({parentWorkloadUuid:'w3',adapterUuid:'a3',executable:'miner'}))).rejects.toThrow('absolute'); expect(d.launcher.spawned[0]!.environment).toEqual({MINER_MODE:'safe'}); d.security.executable=false; await expect(m.launch(request({parentWorkloadUuid:'w4',adapterUuid:'a4'}))).rejects.toThrow('mismatch'); });
 it('records explicit failure, deterministic restart limits, concurrent independence, and orphan cleanup', async () => { const d=deps(); const m=new MinerProcessManager(d); const events:string[]=[]; for(const e of Object.values(MINER_PROCESS_EVENTS)) m.events.subscribe(e,()=>events.push(e)); const one=await m.launch(request()); const two=await m.launch(request({parentWorkloadUuid:'workload-2',adapterUuid:'adapter-2',pluginUuid:'plugin-2',callerId:'workload-2'})); d.launcher.live.delete(one.runtime.pid!); await m.recordExit(one.processUuid,'workload-1',{exitCode:1,timestamp:'2026-08-09T14:00:00.000Z'}); expect(m.registry.require(one.processUuid).runtime.stage).toBe('failed'); await m.restart(one.processUuid,'workload-1','crash-recovery'); expect(m.registry.require(one.processUuid).runtime.stage).toBe('running'); expect(m.registry.require(two.processUuid).runtime.stage).toBe('running'); await m.restart(one.processUuid,'workload-1','automatic'); const exhausted=await m.restart(one.processUuid,'workload-1','automatic'); expect(exhausted.runtime.stage).toBe('degraded'); expect(deterministicBackoff(request().restartPolicy!,3)).toBe(30); d.launcher.live.add(999); const sweep=await m.sweep(true); expect(sweep).toMatchObject({orphanedPids:[999],cleanedPids:[999]}); await m.terminate(one.processUuid,'workload-1'); expect(new Set(events)).toEqual(new Set(Object.values(MINER_PROCESS_EVENTS))); });
});
