import { describe, expect, it } from 'vitest';
import { AsicAlgorithmRegistry, TEST_ASIC_ALGORITHM_PROFILE } from '../src/algorithmAbstraction.js';
import { assertAsicScope, AsicIsolationGuard } from '../src/isolation.js';
import { ASIC_MINING_NOMINAL_LIFECYCLE } from '../src/lifecycle.js';
import { AsicMiningLifecycleStage } from '../src/types.js';
import { config, FakeAsicAdapter, makeFramework } from './testHelpers.js';
describe('IAMF algorithm abstraction, isolation, lifecycle, and secret reference validation', () => {
  it('registers only generic opaque algorithm profiles', () => { const registry = new AsicAlgorithmRegistry(); registry.register(TEST_ASIC_ALGORITHM_PROFILE); expect(registry.require(TEST_ASIC_ALGORITHM_PROFILE.algorithmId)).toEqual(TEST_ASIC_ALGORITHM_PROFILE); expect(registry.list()).toHaveLength(1); expect(() => registry.require('missing')).toThrow('not registered'); });
  it('rejects double claims and cross-ASIC adapter/config control', async () => { const guard = new AsicIsolationGuard(); guard.claim('ASIC-001', 'session-a'); expect(() => guard.claim('ASIC-001', 'session-b')).toThrow('already exclusively claimed'); expect(() => assertAsicScope('ASIC-001', 'ASIC-002')).toThrow('scope violation'); const { framework } = makeFramework(); const first = await framework.start(config(new FakeAsicAdapter())); await expect(framework.start(config(new FakeAsicAdapter()))).rejects.toThrow('already exclusively claimed'); await expect(framework.start(config(new FakeAsicAdapter(), 'ASIC-002', { adapterDeviceUuid: 'ASIC-003' }))).rejects.toThrow('scope violation'); await framework.stop(first.sessionId); });
  it('runs all nine nominal stages, records Failed, and rejects raw credential fields', async () => { const { framework, providers } = makeFramework(); const session = await framework.start(config(new FakeAsicAdapter())); await framework.monitor(session.sessionId); await framework.stop(session.sessionId); expect(framework.getLifecycle(session.sessionId).map((x) => x.to)).toEqual(ASIC_MINING_NOMINAL_LIFECYCLE); expect(providers.calls).toMatchObject({ reserve: 1, release: 1 }); const broken = new FakeAsicAdapter(); broken.failStart = true; await expect(framework.start(config(broken, 'ASIC-002'))).rejects.toThrow('fixture start failure'); expect(framework.registry.byAsic('ASIC-002')[0].stage).toBe(AsicMiningLifecycleStage.Failed); const raw = config(new FakeAsicAdapter(), 'ASIC-003') as unknown as Record<string, unknown>; raw.wallet = 'not-allowed'; await expect(framework.start(raw as never)).rejects.toThrow('raw wallet'); });
});
