import { describe, expect, it } from 'vitest';
import { NormalizedErrorCategory } from '../../mining_adapter_framework/src/types.js';
import { ASIC_MINING_EVENTS } from '../src/events.js';
import { detectAsicFailureConditions } from '../src/failureHandling.js';
import { config, FakeAsicAdapter, makeFramework } from './testHelpers.js';
describe('IAMF ASIC failure detection, events, and explainability', () => {
  it('detects all eight named conditions and normalizes generated conditions through IMAF categories', () => { const { framework } = makeFramework(); const profile = framework.composeAsicProfile('ASIC-001'); profile.powerState.budgetExceeded = true; profile.thermalState.state = 'critical'; profile.deviceHealth.reasons.push('hashboard offline'); const errors = [
    { category: NormalizedErrorCategory.HardwareIncompatible, message: 'ASIC absent', retriable: false }, { category: NormalizedErrorCategory.NetworkFailure, message: 'communication failed', retriable: false }, { category: NormalizedErrorCategory.HardwareIncompatible, message: 'firmware incompatible', retriable: false }, { category: NormalizedErrorCategory.HardwareIncompatible, message: 'hashboard failed', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'thermal overheat', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'power issue', retriable: false }, { category: NormalizedErrorCategory.ProcessFailure, message: 'miner failure', retriable: false }, { category: NormalizedErrorCategory.PoolFailure, message: 'pool failed', retriable: false },
  ]; const found = new Set(errors.flatMap((error, index) => detectAsicFailureConditions({ profile, adapterHealth: { status: index === 6 ? 'faulted' : 'healthy', reasons: index === 3 ? ['hashboard offline'] : index === 7 ? ['pool offline'] : [] }, adapterError: error, asicPresent: index !== 0, at: 't' }).map((condition) => condition.type))); expect(found).toEqual(new Set(['device-disappearance', 'communication-failure', 'firmware-incompatibility', 'hashboard-failure', 'thermal-issues', 'power-issues', 'miner-failure', 'pool-failure'])); });
  it('publishes all ten named events and explains lifecycle, capability, isolation, and failures', async () => { const { framework, providers } = makeFramework(); const received: string[] = []; for (const event of Object.values(ASIC_MINING_EVENTS)) framework.subscribe(event, () => received.push(event)); const session = await framework.start(config(new FakeAsicAdapter())); providers.thermal.getThermalState = () => ({ currentCelsius: 95, state: 'critical', sensorAvailable: true }); providers.power.getPowerState = () => ({ currentWatts: 3500, budgetExceeded: true, state: 'degraded', sensorAvailable: true }); const monitored = await framework.monitor(session.sessionId, { category: NormalizedErrorCategory.PoolFailure, message: 'pool failed', retriable: true }); await framework.stop(session.sessionId); providers.thermal.getThermalState = () => ({ currentCelsius: 65, state: 'nominal', sensorAvailable: true }); providers.power.getPowerState = () => ({ currentWatts: 2000, budgetExceeded: false, state: 'healthy', sensorAvailable: true }); const broken = new FakeAsicAdapter(); broken.failStart = true; await expect(framework.start(config(broken, 'ASIC-002'))).rejects.toThrow('fixture start failure'); expect(new Set(received)).toEqual(new Set(Object.values(ASIC_MINING_EVENTS))); expect(framework.explainLifecycle(session.sessionId).stage).toBe('stopped'); expect(framework.explainCompatibility(session.sessionId).compatible).toBe(true); expect(framework.explainIsolation().isolated).toBe(true); expect(framework.explainFailures(session.sessionId, monitored.failures).degraded).toBe(true); });
});
