import { describe, expect, it } from 'vitest';
import { negotiateAsicCapability } from '../src/capabilityNegotiation.js';
import { composeAsicProfile } from '../src/asicProfile.js';
import { AsicIdentityRegistry } from '../src/multiAsic.js';
import { AsicResourceManagement } from '../src/resourceManagement.js';
import { AsicMiningValidationError } from '../src/errors.js';
import { TEST_ASIC_ALGORITHM_PROFILE } from '../src/algorithmAbstraction.js';
import { config, FakeAsicAdapter, FakeAsicProviders, TEST_ALGORITHM } from './testHelpers.js';
describe('IAMF composed ASIC profile, identity, resource pre-validation, and compatibility', () => {
  it('composes fresh source-owned profiles across Bitmain/Whatsminer/Canaan-shaped fixtures', () => { const p = new FakeAsicProviders(); const first = composeAsicProfile(p, 'ASIC-001'); p.thermal.getThermalState = () => ({ currentCelsius: 81, state: 'warning', sensorAvailable: true }); const second = composeAsicProfile(p, 'ASIC-001'); expect(first).toMatchObject({ asicUuid: 'ASIC-001', manufacturer: 'Bitmain-shaped fixture', firmware: '1.2.0', resourceState: { availableHashboardIds: ['board-1', 'board-2', 'board-3'] }, certificationStatus: { status: 'certified' } }); expect(second.thermalState.currentCelsius).toBe(81); expect(first.thermalState.currentCelsius).toBe(65); });
  it('keeps three ASIC UUIDs independently addressable with no primary ordering assumption', () => { const p = new FakeAsicProviders(); const registry = new AsicIdentityRegistry(p.hardware); expect(registry.list()).toEqual(['ASIC-001', 'ASIC-002', 'ASIC-003']); expect(registry.require('ASIC-001').manufacturer).toContain('Bitmain'); expect(registry.require('ASIC-002').manufacturer).toContain('Whatsminer'); expect(registry.require('ASIC-003').manufacturer).toContain('Canaan'); });
  it('pre-validates device and hashboard availability before IRIA reservation deterministically', () => { const p = new FakeAsicProviders(); const manager = new AsicResourceManagement(p.resource); const profile = composeAsicProfile(p, 'ASIC-001'); const request = { asicUuid: 'ASIC-001', requiredHashboardIds: ['missing'] }; expect(manager.prevalidate(profile, request)).toEqual(manager.prevalidate(profile, request)); expect(() => manager.reserve(profile, { ...request, owner: 'x', requestingAuthority: 'x' })).toThrow(AsicMiningValidationError); expect(p.calls.reserve).toBe(0); expect(manager.reserve(profile, { asicUuid: 'ASIC-001', requiredHashboardIds: ['board-1'], owner: 'x', requestingAuthority: 'x' }).grantedHashboardIds).toEqual(['board-1']); });
  it('negotiates ASIC capability compatibility deterministically for compatible and incompatible inputs', async () => { const p = new FakeAsicProviders(); const adapter = new FakeAsicAdapter(); const manifest = await adapter.identify(); const good = negotiateAsicCapability({ profile: composeAsicProfile(p, 'ASIC-001'), config: config(adapter), manifest, algorithmProfile: TEST_ASIC_ALGORITHM_PROFILE }); const bad = negotiateAsicCapability({ profile: composeAsicProfile(p, 'ASIC-001'), config: { ...config(adapter), algorithm: 'unsupported', deviceSelection: { asicUuid: 'ASIC-001', requiredHashboardIds: ['missing'] } }, manifest, algorithmProfile: { ...TEST_ASIC_ALGORITHM_PROFILE, algorithmId: 'unsupported', minimumFirmwareVersion: '9.0.0' } }); expect(good).toEqual(negotiateAsicCapability({ profile: composeAsicProfile(p, 'ASIC-001'), config: config(adapter), manifest, algorithmProfile: TEST_ASIC_ALGORITHM_PROFILE })); expect(good.compatible).toBe(true); expect(bad.compatible).toBe(false); expect(bad.reasons.join(' ')).toContain('Firmware'); expect(TEST_ALGORITHM).toBe('test-asic-algorithm-fixture'); });
});
