import type { MiningAdapter } from '../../mining_adapter_framework/src/adapterContract.js';
import type { AdapterCapabilities, AdapterDiagnostics, AdapterHealth, AdapterManifest, AdapterPreparationContext, AdapterValidationRequest, AdapterValidationResult, BackendConfig, NormalizedStatistics } from '../../mining_adapter_framework/src/types.js';
import { AsicMiningFramework } from '../src/AsicMiningFramework.js';
import { TEST_ASIC_ALGORITHM_PROFILE } from '../src/algorithmAbstraction.js';
import type { AsicMiningConfig } from '../src/types.js';
import type { AsicMiningProviders } from '../src/providers.js';
export const TEST_ALGORITHM = TEST_ASIC_ALGORITHM_PROFILE.algorithmId;
export class FakeAsicAdapter implements MiningAdapter {
  started = 0; stopped = 0; failStart = false; statisticsValue: unknown = { hashrateHps: 1_000_000_000_000, acceptedShares: 10, rejectedShares: 1, uptimeSeconds: 120, workerStatus: 'running', temperatureCelsius: 65, powerWatts: 2000, poolLatencyMs: 42, extensions: { invalidShares: 0, hardwareErrors: 0 } }; healthValue: AdapterHealth = { status: 'healthy', reasons: [] };
  async identify(): Promise<AdapterManifest> { return { adapterId: 'fake-asic-adapter', name: 'Fake ASIC Adapter', version: '1', vendor: 'fixture', backend: 'fixture', supportedOperatingSystems: ['test'], supportedHardware: ['asic'], supportedAlgorithms: [TEST_ALGORITHM], supportedProtocols: ['fixture-pool'], requiredCapabilities: [], supportedFeatures: [], configurationSchema: {}, minimumFrameworkVersion: '1', certificationStatus: 'development' }; }
  async validate(_r: AdapterValidationRequest): Promise<AdapterValidationResult> { return { valid: true, reasons: [] }; } async configure(_c: BackendConfig): Promise<void> {} async prepare(_c: AdapterPreparationContext): Promise<void> {} async start(): Promise<void> { this.started++; if (this.failStart) throw new Error('fixture start failure'); } async pause(): Promise<void> {} async resume(): Promise<void> {} async stop(): Promise<void> { this.stopped++; } async restart(): Promise<void> {} async health(): Promise<AdapterHealth> { return this.healthValue; } async statistics(): Promise<unknown> { return this.statisticsValue; } async capabilities(): Promise<AdapterCapabilities> { return { operatingSystems: ['test'], hardware: ['asic'], algorithms: [TEST_ALGORITHM], protocols: ['fixture-pool'], statistics: ['hashrateHps'], controlOperations: ['start', 'stop'], features: [] }; } async diagnostics(): Promise<AdapterDiagnostics> { return { details: {} }; } async cleanup(): Promise<void> {}
}
type Allocation = { deviceAvailable: boolean; allocated: boolean; availableHashboardIds: string[]; allocatedHashboardIds: string[]; contentionReasons: string[] };
export class FakeAsicProviders implements AsicMiningProviders {
  calls = { reserve: 0, release: 0, mutation: 0 }; ids = ['ASIC-001', 'ASIC-002', 'ASIC-003']; allocations: Record<string, Allocation> = {};
  constructor() { for (const id of this.ids) this.allocations[id] = { deviceAvailable: true, allocated: false, availableHashboardIds: ['board-1', 'board-2', 'board-3'], allocatedHashboardIds: [], contentionReasons: [] }; }
  hardware = { listAsics: () => [...this.ids], getAsic: (id: string) => ({ asicUuid: id, manufacturer: id === 'ASIC-001' ? 'Bitmain-shaped fixture' : id === 'ASIC-002' ? 'Whatsminer-shaped fixture' : 'Canaan-shaped fixture', model: id === 'ASIC-001' ? 'fixture-ant-style' : id === 'ASIC-002' ? 'fixture-micro-style' : 'fixture-avalon-style', firmware: '1.2.0', hardwareRevision: 'fixture-rev-a', algorithms: [TEST_ALGORITHM], hashrateCapabilityHps: 1_500_000_000_000, powerProfile: { maximumRatedWatts: 3500, nominalWatts: 3000 }, thermalProfile: { warningThresholdCelsius: 80, criticalThresholdCelsius: 90 }, networkIdentity: { address: `10.0.0.${id.slice(-1)}`, hostname: id, accessible: true } }) };
  resource = { reserve: (request: { asicUuid: string; requiredHashboardIds: string[] }) => { this.calls.reserve++; return { reservationId: `reservation-${this.calls.reserve}`, asicUuid: request.asicUuid, grantedHashboardIds: [...request.requiredHashboardIds] }; }, release: (_id: string, _reason: string) => { this.calls.release++; }, getAllocation: (id: string) => ({ ...this.allocations[id], availableHashboardIds: [...this.allocations[id].availableHashboardIds], allocatedHashboardIds: [...this.allocations[id].allocatedHashboardIds], contentionReasons: [...this.allocations[id].contentionReasons] }) };
  thermal = { getThermalState: (_id: string) => ({ currentCelsius: 65, state: 'nominal' as const, warningThresholdCelsius: 80, criticalThresholdCelsius: 90, sensorAvailable: true }) };
  power = { getPowerState: (_id: string) => ({ currentWatts: 2000, maximumRatedWatts: 3500, budgetLimitWatts: 3000, budgetExceeded: false, state: 'healthy' as const, sensorAvailable: true }) };
  health = { getDeviceHealth: (_id: string) => ({ status: 'healthy' as const, reasons: [], reliability: .99, observedAt: '2026-08-09T14:00:00.000Z' }) };
  certification = { getCertificationStatus: (_id: string) => ({ status: 'certified' as const, certificationId: 'cert-asic' }) };
}
export function config(adapter: MiningAdapter, asicUuid = 'ASIC-001', overrides: Partial<AsicMiningConfig> = {}): AsicMiningConfig { return { asicUuid, algorithm: TEST_ALGORITHM, pool: { endpoint: 'fixture://pool', protocol: 'fixture-pool', credentialReference: 'opaque-pool-credential-reference' }, walletReference: 'opaque-wallet-reference', workerIdentity: `worker-${asicUuid}`, deviceSelection: { asicUuid, requiredHashboardIds: ['board-1'] }, performancePolicyReference: 'opaque-performance-policy', powerPolicyReference: 'opaque-power-policy', thermalPolicyReference: 'opaque-thermal-policy', networkConfigurationReference: 'opaque-network-configuration', backendAdapter: adapter, ...overrides }; }
export function makeFramework(providers = new FakeAsicProviders()) { const framework = new AsicMiningFramework({ providers, now: () => '2026-08-09T14:00:00.000Z' }); framework.algorithms.register(TEST_ASIC_ALGORITHM_PROFILE); return { framework, providers }; }
export function normalized(overrides: Partial<NormalizedStatistics> = {}): NormalizedStatistics { return { hashrateHps: 1_000_000_000_000, acceptedShares: 10, rejectedShares: 1, uptimeSeconds: 120, temperatureCelsius: 65, powerWatts: 2000, poolLatencyMs: 42, extensions: { invalidShares: 0, hardwareErrors: 0 }, ...overrides }; }
