import type { InstitutionalEventBus } from '../../event_bus/src/index.js';
import { AsicAlgorithmRegistry } from './algorithmAbstraction.js';
import { AsicProfileComposer } from './asicProfile.js';
import { negotiateAsicCapability } from './capabilityNegotiation.js';
import { AsicFleetDigitalTwin } from './digitalTwin.js';
import { AsicMiningValidationError } from './errors.js';
import { ASIC_MINING_EVENTS, AsicMiningEventBus, type AsicMiningEventName } from './events.js';
import { explainAsicCapability, explainAsicFailures, explainAsicIsolation, explainAsicLifecycle } from './explainability.js';
import { detectAsicFailureConditions } from './failureHandling.js';
import { assertAsicScope, AsicIsolationGuard } from './isolation.js';
import { assertAsicMiningLifecycleTransition } from './lifecycle.js';
import { AsicIdentityRegistry } from './multiAsic.js';
import { recommendAsicOptimization } from './optimizationTelemetry.js';
import { AsicPerformanceHistory } from './performance.js';
import type { AsicMiningProviders } from './providers.js';
import { AsicMiningSessionRegistry } from './registry.js';
import { AsicResourceManagement } from './resourceManagement.js';
import { AsicMiningLifecycleStage } from './types.js';
import type { AsicFailureCondition, AsicMiningConfig, AsicMiningLifecycleRecord, AsicMiningSession, AsicOptimizationRecommendation, AsicPerformanceRecord, AsicProfile, NormalizedError, NormalizedStatistics } from './types.js';

export interface AsicMiningFrameworkOptions { providers: AsicMiningProviders; eventBus?: InstitutionalEventBus; now?: () => string; }
/** IAMF composes one UUID-scoped ASIC session around each injected IMAF MiningAdapter reference. It does not recreate adapter lifecycle, protocol behavior, or backend configuration. */
export class AsicMiningFramework {
  readonly algorithms = new AsicAlgorithmRegistry(); readonly profiles: AsicProfileComposer; readonly asics: AsicIdentityRegistry; readonly resources: AsicResourceManagement; readonly isolation = new AsicIsolationGuard(); readonly performance = new AsicPerformanceHistory(); readonly digitalTwin = new AsicFleetDigitalTwin(); readonly events: AsicMiningEventBus; readonly registry: AsicMiningSessionRegistry;
  private readonly lifecycleRecords: AsicMiningLifecycleRecord[] = []; private readonly providers: AsicMiningProviders; private readonly nowFn: () => string; private sequence = 0;
  constructor(options: AsicMiningFrameworkOptions) { this.providers = options.providers; this.profiles = new AsicProfileComposer(options.providers); this.asics = new AsicIdentityRegistry(options.providers.hardware); this.resources = new AsicResourceManagement(options.providers.resource); this.events = new AsicMiningEventBus(options.eventBus); this.registry = new AsicMiningSessionRegistry(this.isolation); this.nowFn = options.now ?? (() => new Date().toISOString()); }
  composeAsicProfile(asicUuid: string): AsicProfile { return this.profiles.compose(asicUuid); }
  async start(config: AsicMiningConfig): Promise<AsicMiningSession> {
    this.assertConfigShape(config); this.asics.require(config.asicUuid); assertAsicScope(config.asicUuid, config.deviceSelection.asicUuid); assertAsicScope(config.asicUuid, config.adapterDeviceUuid ?? config.asicUuid);
    const session: AsicMiningSession = { sessionId: `asic-session-${++this.sequence}`, config, stage: AsicMiningLifecycleStage.Requested };
    try {
      this.registry.add(session); this.transition(session, AsicMiningLifecycleStage.Requested, 'ASIC mining request accepted with UUID-scoped identity.'); this.events.publish(ASIC_MINING_EVENTS.AsicDiscovered, { sessionId: session.sessionId, asicUuid: config.asicUuid });
      const profile = this.profiles.compose(config.asicUuid); const manifest = config.backendManifest ?? await config.backendAdapter.identify(); const algorithmProfile = this.algorithms.require(config.algorithm); const compatibility = negotiateAsicCapability({ profile, config, manifest, algorithmProfile }); session.compatibility = compatibility;
      if (!compatibility.compatible) throw new AsicMiningValidationError(`ASIC capability negotiation failed: ${compatibility.reasons.join(' ')}`);
      this.transition(session, AsicMiningLifecycleStage.Validated, 'Deterministic ASIC, firmware, adapter, network, policy, resource, and certification checks passed.'); this.events.publish(ASIC_MINING_EVENTS.AsicValidated, { sessionId: session.sessionId, asicUuid: config.asicUuid, compatibility });
      const grant = this.resources.reserve(profile, { asicUuid: config.asicUuid, requiredHashboardIds: config.deviceSelection.requiredHashboardIds, owner: config.workerIdentity, requestingAuthority: 'ASIC Mining Framework' });
      assertAsicScope(config.asicUuid, grant.asicUuid); if (grant.grantedHashboardIds.length !== new Set(config.deviceSelection.requiredHashboardIds).size || !grant.grantedHashboardIds.every((id) => config.deviceSelection.requiredHashboardIds.includes(id))) throw new AsicMiningValidationError('IRIA returned a grant that does not match the requested ASIC UUID or hashboard resources.');
      session.grant = grant; this.transition(session, AsicMiningLifecycleStage.ResourceReserved, 'IRIA-shaped provider granted ASIC and hashboard reservation.'); this.transition(session, AsicMiningLifecycleStage.Configured, 'ASIC session references an adapter configured through IMAF/composition root.'); this.transition(session, AsicMiningLifecycleStage.Prepared, 'UUID-scoped grant and injected adapter are ready.');
      await config.backendAdapter.start(); this.transition(session, AsicMiningLifecycleStage.Started, 'Injected IMAF MiningAdapter start contract completed.'); this.transition(session, AsicMiningLifecycleStage.Running, 'ASIC mining session is running on its exclusively claimed UUID.'); this.events.publish(ASIC_MINING_EVENTS.AsicMiningStarted, { sessionId: session.sessionId, asicUuid: config.asicUuid }); return this.snapshot(session);
    } catch (error) { await this.fail(session, error); throw error; }
  }
  async monitor(sessionId: string, adapterError?: NormalizedError): Promise<{ record: AsicPerformanceRecord; failures: AsicFailureCondition[]; recommendations: AsicOptimizationRecommendation[] }> {
    const session = this.registry.assertActiveOwnership(sessionId); if (!session.grant) throw new AsicMiningValidationError('Only a resource-reserved ASIC session can be monitored.'); assertAsicScope(session.grant.asicUuid, session.config.adapterDeviceUuid ?? session.config.asicUuid);
    try {
      const profile = this.profiles.compose(session.config.asicUuid); const statistics = asNormalizedStatistics(await session.config.backendAdapter.statistics()); const health = await session.config.backendAdapter.health(); const record = this.performance.record(sessionId, profile, statistics, this.nowFn()); this.digitalTwin.record({ sessionId, profile, algorithm: session.config.algorithm, performance: record });
      if (session.stage === AsicMiningLifecycleStage.Running) this.transition(session, AsicMiningLifecycleStage.Monitored, 'Adapter statistics and provider-composed health sampled through existing contracts.'); this.events.publish(ASIC_MINING_EVENTS.AsicHashrateUpdated, { sessionId, record }); this.events.publish(ASIC_MINING_EVENTS.AsicEfficiencyUpdated, { sessionId, efficiencyHpsPerWatt: record.efficiencyHpsPerWatt });
      const failures = detectAsicFailureConditions({ profile, adapterHealth: health, adapterError, asicPresent: this.asics.has(session.config.asicUuid), at: this.nowFn() }); for (const failure of failures) { if (failure.type === 'thermal-issues') this.events.publish(ASIC_MINING_EVENTS.AsicThermalWarning, { sessionId, failure }); if (failure.type === 'power-issues') this.events.publish(ASIC_MINING_EVENTS.AsicPowerWarning, { sessionId, failure }); } if (failures.length) this.events.publish(ASIC_MINING_EVENTS.AsicDegraded, { sessionId, failures }); return { record, failures, recommendations: recommendAsicOptimization(profile, { algorithm: session.config.algorithm }, record) };
    } catch (error) { await this.fail(session, error); throw error; }
  }
  async stop(sessionId: string): Promise<AsicMiningSession> { const session = this.registry.assertActiveOwnership(sessionId); assertAsicScope(session.grant?.asicUuid ?? session.config.asicUuid, session.config.adapterDeviceUuid ?? session.config.asicUuid); try { await session.config.backendAdapter.stop(); this.transition(session, AsicMiningLifecycleStage.Stopped, 'Injected IMAF MiningAdapter stop contract completed.'); this.release(session, 'ASIC mining session stopped.'); this.events.publish(ASIC_MINING_EVENTS.AsicMiningStopped, { sessionId, asicUuid: session.config.asicUuid }); return this.snapshot(session); } catch (error) { await this.fail(session, error); throw error; } }
  getSession(sessionId: string): AsicMiningSession { return this.snapshot(this.requireSession(sessionId)); } getLifecycle(sessionId: string): AsicMiningLifecycleRecord[] { this.requireSession(sessionId); return this.lifecycleRecords.filter((record) => record.sessionId === sessionId); } getPerformance(sessionId: string): AsicPerformanceRecord[] { this.requireSession(sessionId); return this.performance.forSession(sessionId); } getRecommendations(sessionId: string): AsicOptimizationRecommendation[] { const session = this.requireSession(sessionId); return recommendAsicOptimization(this.profiles.compose(session.config.asicUuid), { algorithm: session.config.algorithm }, this.performance.forSession(sessionId).at(-1)); } explainLifecycle(sessionId: string) { return explainAsicLifecycle(this.getLifecycle(sessionId)); } explainCompatibility(sessionId: string) { const result = this.requireSession(sessionId).compatibility; if (!result) throw new AsicMiningValidationError('Session has no capability negotiation result yet.'); return explainAsicCapability(result); } explainFailures(sessionId: string, failures: AsicFailureCondition[]) { this.requireSession(sessionId); return explainAsicFailures(failures); } explainIsolation(error?: Error) { return explainAsicIsolation(error); } subscribe(event: AsicMiningEventName, handler: (payload: unknown) => void): () => void { return this.events.subscribe(event, handler); }
  private requireSession(sessionId: string): AsicMiningSession { return this.registry.require(sessionId); } private transition(session: AsicMiningSession, to: AsicMiningLifecycleStage, reason: string): void { const from = this.lifecycleRecords.filter((record) => record.sessionId === session.sessionId).at(-1)?.to; assertAsicMiningLifecycleTransition(from, to); session.stage = to; this.lifecycleRecords.push(Object.freeze({ sessionId: session.sessionId, from, to, at: this.nowFn(), reason })); } private async fail(session: AsicMiningSession, error: unknown): Promise<void> { const registered = this.lifecycleRecords.some((record) => record.sessionId === session.sessionId); if (registered && session.stage !== AsicMiningLifecycleStage.Failed && session.stage !== AsicMiningLifecycleStage.Stopped) this.transition(session, AsicMiningLifecycleStage.Failed, `ASIC mining failure: ${error instanceof Error ? error.message : String(error)}`); this.release(session, 'ASIC mining session failed.'); this.events.publish(ASIC_MINING_EVENTS.AsicMiningFailed, { sessionId: session.sessionId, asicUuid: session.config.asicUuid, error: error instanceof Error ? error.message : String(error) }); } private release(session: AsicMiningSession, reason: string): void { if (session.grant) { this.providers.resource.release(session.grant.reservationId, reason); session.grant = undefined; } this.registry.release(session); } private snapshot(session: AsicMiningSession): AsicMiningSession { return { ...session, config: session.config, grant: session.grant ? { ...session.grant, grantedHashboardIds: [...session.grant.grantedHashboardIds] } : undefined, compatibility: session.compatibility ? { ...session.compatibility, checks: [...session.compatibility.checks], reasons: [...session.compatibility.reasons] } : undefined }; }
  private assertConfigShape(config: AsicMiningConfig): void { const unsafe = config as unknown as Record<string, unknown>; const pool = config.pool as unknown as Record<string, unknown>; if (['wallet', 'walletAddress', 'password', 'poolPassword', 'credentials', 'privateKey', 'secret'].some((key) => Object.hasOwn(unsafe, key) || Object.hasOwn(pool, key))) throw new AsicMiningValidationError('ASIC mining config permits opaque references only; raw wallet or pool credentials are prohibited.'); if (!config.asicUuid.trim() || !config.algorithm.trim() || !config.walletReference.trim() || !config.workerIdentity.trim() || !config.pool.endpoint.trim() || !config.pool.protocol.trim() || config.deviceSelection.asicUuid !== config.asicUuid || !config.deviceSelection.requiredHashboardIds.length) throw new AsicMiningValidationError('ASIC mining config requires UUID-scoped selection, opaque algorithm/wallet references, worker, pool endpoint/protocol, and at least one hashboard resource.'); }
}
function asNormalizedStatistics(raw: unknown): NormalizedStatistics { if (!raw || typeof raw !== 'object' || !('extensions' in raw)) throw new AsicMiningValidationError('IAMF requires IMAF-normalized adapter statistics with an extensions field.'); return raw as NormalizedStatistics; }
