import type { AsicFailureCondition, AsicProfile, NormalizedError } from './types.js';
/** Detection and reporting only: no restart, recovery, allocation, policy override, or protocol action is performed. */
export function detectAsicFailureConditions(input: { profile: AsicProfile; adapterHealth?: { status: string; reasons: string[] }; adapterError?: NormalizedError; asicPresent: boolean; at: string }): AsicFailureCondition[] {
  const conditions: AsicFailureCondition[] = []; const error = input.adapterError; const healthReasons = input.adapterHealth?.reasons ?? []; const add = (type: AsicFailureCondition['type'], severity: AsicFailureCondition['severity'], rationale: string, normalizedError?: NormalizedError) => conditions.push(Object.freeze({ type, severity, detectedAt: input.at, rationale, normalizedError, evidence: Object.freeze({ asicUuid: input.profile.asicUuid, deviceHealth: input.profile.deviceHealth, adapterHealth: input.adapterHealth, adapterError: error }) }));
  if (!input.asicPresent) add('device-disappearance', 'critical', 'Injected hardware provider no longer identifies the ASIC UUID.', error ?? normalize('HardwareIncompatible' as NormalizedError['category'], 'ASIC disappeared.'));
  if (error?.category === 'NetworkFailure' || /communication|network api|device api/i.test(error?.message ?? '') || healthReasons.some((reason) => /communication/i.test(reason))) add('communication-failure', 'error', 'Adapter or provider signal indicates ASIC communication failure.', error ?? normalize('NetworkFailure' as NormalizedError['category'], 'ASIC communication failure.'));
  if (error?.category === 'HardwareIncompatible' && /firmware/i.test(error.message) || /firmware/i.test(error?.message ?? '')) add('firmware-incompatibility', 'error', 'Adapter signal indicates firmware incompatibility.', error ?? normalize('HardwareIncompatible' as NormalizedError['category'], 'ASIC firmware incompatibility.'));
  if (/hashboard/i.test(error?.message ?? '') || healthReasons.some((reason) => /hashboard/i.test(reason)) || input.profile.deviceHealth.reasons.some((reason) => /hashboard/i.test(reason))) add('hashboard-failure', 'critical', 'Health or adapter signal indicates a hashboard failure.', error ?? normalize('HardwareIncompatible' as NormalizedError['category'], 'ASIC hashboard failure.'));
  if (['warning', 'critical'].includes(input.profile.thermalState.state) || /thermal|overheat/i.test(error?.message ?? '')) add('thermal-issues', input.profile.thermalState.state === 'critical' ? 'critical' : 'warning', 'Thermal provider or adapter signal indicates ASIC thermal issues.', error);
  if (input.profile.powerState.budgetExceeded || input.profile.powerState.state === 'faulted' || /power/i.test(error?.message ?? '')) add('power-issues', 'warning', 'Power provider or adapter signal indicates ASIC power issues.', error);
  if (input.adapterHealth?.status === 'faulted' || error?.category === 'ProcessFailure') add('miner-failure', 'critical', 'Adapter health/error indicates miner failure.', error);
  if (error?.category === 'PoolFailure' || /pool/i.test(error?.message ?? '') || healthReasons.some((reason) => /pool/i.test(reason))) add('pool-failure', 'warning', 'Adapter health/error indicates pool failure.', error);
  return conditions;
}
function normalize(category: NormalizedError['category'], message: string): NormalizedError { return { category, message, retriable: false, source: 'IAMF detection' }; }
