import type { InstitutionalEventBus } from '../../event_bus/src/index.js';
import type { NormalizedError, NormalizedStatistics } from '../../mining_adapter_framework/src/types.js';
import { negotiateGpuCapability } from './capabilityNegotiation.js';
import { GpuMiningDigitalTwin } from './digitalTwin.js';
import { GpuMiningValidationError } from './errors.js';
import { GPU_MINING_EVENTS, GpuMiningEventBus, type GpuMiningEventName } from './events.js';
import { explainGpuCapability, explainGpuFailures, explainGpuIsolation, explainGpuLifecycle } from './explainability.js';
import { detectGpuFailureConditions } from './failureHandling.js';
import { GpuProfileComposer } from './gpuProfile.js';
import { GpuIsolationGuard } from './isolation.js';
import { assertGpuMiningLifecycleTransition } from './lifecycle.js';
import { GpuIdentityRegistry } from './multiGpu.js';
import { recommendGpuOptimization } from './optimizationTelemetry.js';
import { GpuPerformanceHistory } from './performance.js';
import type { GpuMiningProviders } from './providers.js';
import { GpuMiningSessionRegistry } from './registry.js';
import { GpuMiningLifecycleStage } from './types.js';
import type { GpuCapabilityNegotiationResult, GpuFailureCondition, GpuMiningConfig, GpuMiningLifecycleRecord, GpuMiningSession, GpuOptimizationRecommendation, GpuPerformanceRecord, GpuProfile } from './types.js';
import { VramManagement } from './vramManagement.js';
export interface GpuMiningFrameworkOptions { providers: GpuMiningProviders; eventBus?: InstitutionalEventBus; now?: () => string; }
/** IGMF surrounds injected IMAF MiningAdapter contracts; each session keeps its own GPU UUID and adapter reference. */
export class GpuMiningFramework {
  readonly profiles: GpuProfileComposer; readonly gpus: GpuIdentityRegistry; readonly vram: VramManagement; readonly isolation = new GpuIsolationGuard(); readonly performance = new GpuPerformanceHistory(); readonly digitalTwin = new GpuMiningDigitalTwin(); readonly events: GpuMiningEventBus; readonly registry: GpuMiningSessionRegistry;
  private readonly lifecycleRecords: GpuMiningLifecycleRecord[] = []; private readonly providers: GpuMiningProviders; private readonly nowFn: () => string; private sequence = 0;
  constructor(options: GpuMiningFrameworkOptions) { this.providers = options.providers; this.profiles = new GpuProfileComposer(options.providers); this.gpus = new GpuIdentityRegistry(options.providers.hardware); this.vram = new VramManagement(options.providers.resource); this.events = new GpuMiningEventBus(options.eventBus); this.registry = new GpuMiningSessionRegistry(this.isolation); this.nowFn = options.now ?? (() => new Date().toISOString()); }
  composeGpuProfile(gpuUuid: string): GpuProfile { return this.profiles.compose(gpuUuid); }
  async start(config: GpuMiningConfig): Promise<GpuMiningSession> { this.assertConfigShape(config); this.gpus.require(config.gpuUuid); const session: GpuMiningSession = { sessionId: `gpu-session-${++this.sequence}`, config, stage: GpuMiningLifecycleStage.Requested }; this.registry.add(session); this.transition(session, GpuMiningLifecycleStage.Requested, 'GPU mining request accepted with UUID-scoped identity.'); this.events.publish(GPU_MINING_EVENTS.GpuMiningRequested, { sessionId: session.sessionId, gpuUuid: config.gpuUuid }); try { const profile = this.profiles.compose(config.gpuUuid); const manifest = config.backendManifest ?? await config.backendAdapter.identify(); const compatibility = negotiateGpuCapability({ profile, config, manifest, requiredVramMB: config.memoryConfiguration.requiredVramMB }); session.compatibility = compatibility; if (!compatibility.compatible) throw new GpuMiningValidationError(`GPU capability negotiation failed: ${compatibility.reasons.join(' ')}`); this.transition(session, GpuMiningLifecycleStage.GpuCompatibilityVerified, 'Deterministic GPU capability and adapter manifest checks passed.'); const grant = this.vram.reserve(profile, { gpuUuid: config.gpuUuid, requiredVramMB: config.memoryConfiguration.requiredVramMB, requestedComputeQueues: 1, owner: config.workerIdentity, requestingAuthority: 'GPU Mining Framework' }); if (grant.gpuUuid !== config.gpuUuid || grant.grantedVramMB < config.memoryConfiguration.requiredVramMB || grant.grantedComputeQueues < 1) throw new GpuMiningValidationError('IRIA returned a grant that does not match the requested GPU UUID, VRAM, or compute queue requirement.'); session.grant = grant; this.transition(session, GpuMiningLifecycleStage.ResourceReserved, 'IRIA-shaped provider granted GPU VRAM and compute queue reservation.'); this.transition(session, GpuMiningLifecycleStage.Configured, 'GPU session references an adapter configured through IMAF/composition root.'); this.transition(session, GpuMiningLifecycleStage.Prepared, 'UUID-scoped grant and injected adapter are ready.'); this.events.publish(GPU_MINING_EVENTS.GpuMiningPrepared, { sessionId: session.sessionId, gpuUuid: config.gpuUuid, reservationId: grant.reservationId }); await config.backendAdapter.start(); this.transition(session, GpuMiningLifecycleStage.Started, 'Injected IMAF MiningAdapter start contract completed.'); this.transition(session, GpuMiningLifecycleStage.Running, 'GPU mining session is running on its exclusively claimed UUID.'); this.events.publish(GPU_MINING_EVENTS.GpuMiningStarted, { sessionId: session.sessionId, gpuUuid: config.gpuUuid }); return this.snapshot(session); } catch (error) { await this.fail(session, error); throw error; } }
  async monitor(sessionId: string, adapterError?: NormalizedError): Promise<{ record: GpuPerformanceRecord; failures: GpuFailureCondition[]; recommendations: GpuOptimizationRecommendation[] }> { const session = this.requireSession(sessionId); if (!session.grant) throw new GpuMiningValidationError('Only a resource-reserved GPU session can be monitored.'); try { const profile = this.profiles.compose(session.config.gpuUuid); const statistics = asNormalizedStatistics(await session.config.backendAdapter.statistics()); const health = await session.config.backendAdapter.health(); const record = this.performance.record(sessionId, profile, statistics, this.nowFn()); this.digitalTwin.record({ sessionId, profile, algorithm: session.config.algorithm, configuration: { intensity: session.config.intensity, requiredVramMB: session.config.memoryConfiguration.requiredVramMB }, performance: record }); if (session.stage === GpuMiningLifecycleStage.Running) this.transition(session, GpuMiningLifecycleStage.Monitored, 'Adapter statistics and health sampled via existing contract methods.'); this.events.publish(GPU_MINING_EVENTS.GpuHashrateUpdated, { sessionId, record }); this.events.publish(GPU_MINING_EVENTS.GpuEfficiencyUpdated, { sessionId, hashratePerWatt: record.hashratePerWatt }); const failures = detectGpuFailureConditions({ profile, requiredVramMB: session.config.memoryConfiguration.requiredVramMB, adapterHealth: health, adapterError, gpuPresent: this.gpus.has(session.config.gpuUuid), at: this.nowFn() }); for (const failure of failures) { if (failure.type === 'thermal-throttling') this.events.publish(GPU_MINING_EVENTS.GpuThermalWarning, { sessionId, failure }); if (failure.type === 'power-limit-violation') this.events.publish(GPU_MINING_EVENTS.GpuPowerWarning, { sessionId, failure }); } if (failures.length) this.events.publish(GPU_MINING_EVENTS.GpuDegraded, { sessionId, failures }); return { record, failures, recommendations: recommendGpuOptimization(profile, { intensity: session.config.intensity, requiredVramMB: session.config.memoryConfiguration.requiredVramMB }, record) }; } catch (error) { await this.fail(session, error); throw error; } }
  async stop(sessionId: string): Promise<GpuMiningSession> { const session = this.requireSession(sessionId); try { await session.config.backendAdapter.stop(); this.transition(session, GpuMiningLifecycleStage.Stopped, 'Injected IMAF MiningAdapter stop contract completed.'); this.release(session, 'GPU mining session stopped.'); this.events.publish(GPU_MINING_EVENTS.GpuMiningStopped, { sessionId, gpuUuid: session.config.gpuUuid }); return this.snapshot(session); } catch (error) { await this.fail(session, error); throw error; } }
  getSession(sessionId: string): GpuMiningSession { return this.snapshot(this.requireSession(sessionId)); } getLifecycle(sessionId: string): GpuMiningLifecycleRecord[] { this.requireSession(sessionId); return this.lifecycleRecords.filter((record) => record.sessionId === sessionId); } getPerformance(sessionId: string): GpuPerformanceRecord[] { this.requireSession(sessionId); return this.performance.forSession(sessionId); } getRecommendations(sessionId: string): GpuOptimizationRecommendation[] { const session = this.requireSession(sessionId); return recommendGpuOptimization(this.profiles.compose(session.config.gpuUuid), { intensity: session.config.intensity, requiredVramMB: session.config.memoryConfiguration.requiredVramMB }, this.performance.forSession(sessionId).at(-1)); } explainLifecycle(sessionId: string) { return explainGpuLifecycle(this.getLifecycle(sessionId)); } explainCompatibility(sessionId: string) { const result = this.requireSession(sessionId).compatibility; if (!result) throw new GpuMiningValidationError('Session has no capability negotiation result yet.'); return explainGpuCapability(result); } explainFailures(sessionId: string, failures: GpuFailureCondition[]) { this.requireSession(sessionId); return explainGpuFailures(failures); } explainIsolation(error?: Error) { return explainGpuIsolation(error); } subscribe(event: GpuMiningEventName, handler: (payload: unknown) => void): () => void { return this.events.subscribe(event, handler); }
  private requireSession(sessionId: string): GpuMiningSession { return this.registry.require(sessionId); } private transition(session: GpuMiningSession, to: GpuMiningLifecycleStage, reason: string): void { const from = this.lifecycleRecords.filter((record) => record.sessionId === session.sessionId).at(-1)?.to; assertGpuMiningLifecycleTransition(from, to); session.stage = to; this.lifecycleRecords.push(Object.freeze({ sessionId: session.sessionId, from, to, at: this.nowFn(), reason })); } private async fail(session: GpuMiningSession, error: unknown): Promise<void> { if (session.stage !== GpuMiningLifecycleStage.Failed && session.stage !== GpuMiningLifecycleStage.Stopped) this.transition(session, GpuMiningLifecycleStage.Failed, `GPU mining failure: ${error instanceof Error ? error.message : String(error)}`); this.release(session, 'GPU mining session failed.'); this.events.publish(GPU_MINING_EVENTS.GpuMiningFailed, { sessionId: session.sessionId, gpuUuid: session.config.gpuUuid, error: error instanceof Error ? error.message : String(error) }); } private release(session: GpuMiningSession, reason: string): void { if (session.grant) { this.providers.resource.releaseVram(session.grant.reservationId, reason); session.grant = undefined; } this.registry.release(session); } private snapshot(session: GpuMiningSession): GpuMiningSession { return { ...session, config: session.config, grant: session.grant ? { ...session.grant } : undefined, compatibility: session.compatibility ? { ...session.compatibility, checks: [...session.compatibility.checks], reasons: [...session.compatibility.reasons] } : undefined }; } private assertConfigShape(config: GpuMiningConfig): void { const unsafe = config as unknown as Record<string, unknown>; const pool = config.pool as unknown as Record<string, unknown>; if (['wallet', 'walletAddress', 'password', 'poolPassword', 'credentials'].some((key) => Object.hasOwn(unsafe, key) || Object.hasOwn(pool, key))) throw new GpuMiningValidationError('GPU mining config permits opaque references only; raw wallet or pool credentials are prohibited.'); if (!config.gpuUuid.trim() || !config.algorithm.trim() || !config.walletReference.trim() || !config.workerIdentity.trim() || !config.pool.endpoint.trim() || !Number.isFinite(config.intensity) || config.memoryConfiguration.requiredVramMB <= 0) throw new GpuMiningValidationError('GPU mining config requires UUID, opaque algorithm/wallet references, worker, pool endpoint, finite intensity, and positive required VRAM.'); } }
function asNormalizedStatistics(raw: unknown): NormalizedStatistics { if (!raw || typeof raw !== 'object' || !('extensions' in raw)) throw new GpuMiningValidationError('IGMF requires IMAF-normalized adapter statistics with an extensions field.'); return raw as NormalizedStatistics; }
