import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { makeAuthority, pipelineAndCertify } from './testHelpers.js';
const root=fileURLToPath(new URL('../src/',import.meta.url));
function sourceTree(path: string): string { return readdirSync(path,{withFileTypes:true}).flatMap((entry)=>entry.isDirectory()? [sourceTree(`${path}/${entry.name}`)] : entry.name.endsWith('.ts')?[readFileSync(`${path}/${entry.name}`,'utf8')]:[]).join('\n'); }
describe('IMPCA IMPR seam compatibility and authority boundaries', () => {
  it('returns exactly the Phase 30 PluginCertificationStatusProvider structural output fields', async () => { const {authority}=await pipelineAndCertify(); const status=authority.getCertificationStatus({pluginUuid:'plugin-001',version:'1.0.0'}); expect(Object.keys(status).sort()).toEqual(['certified','level','reason']); expect(status).toMatchObject({certified:true,level:expect.any(String),reason:expect.any(String)}); });
  it('does not import or instantiate any implementation authority/framework, including IHCA', () => { const source=sourceTree(root); expect(source).not.toMatch(/from\s+['"][^'"]*(?:hardware_authority|resource_authority|power_authority|thermal_authority|health_authority|security_authority|certification_authority|arbitration_authority|benchmark_authority|workload_authority|scheduling_authority|observability_authority|data_authority|storage_authority|mining_adapter_framework|cpu_mining_framework|gpu_mining_framework|asic_mining_framework|miner_process_manager|mining_statistics_framework|mining_plugin_runtime)[^'"]*['"]/); expect(source).not.toMatch(/new\s+(?:HardwareAuthority|ResourceAuthority|PowerAuthority|ThermalAuthority|HealthAuthority|SecurityAuthority|CertificationAuthority|ArbitrationAuthority|BenchmarkAuthority|WorkloadAuthority|SchedulingAuthority|ObservabilityAuthority|DataAuthority|StorageAuthority|MiningAdapterFramework|CpuMiningFramework|GpuMiningFramework|AsicMiningFramework|MinerProcessManager|MiningStatisticsFramework|MiningPluginRuntime)\b/); });
  it('is deterministic given identical injected providers, clock, and UUID sequence', async () => { const first=makeAuthority(); const second=makeAuthority(); const a=first.submit({pluginUuid:'deterministic',version:'1',manifest:{}}); const b=second.submit({pluginUuid:'deterministic',version:'1',manifest:{}}); await first.runPipeline(a.certificationId,{}); await second.runPipeline(b.certificationId,{}); const left=await first.certify(a.certificationId); const right=await second.certify(b.certificationId); expect(right).toEqual(left); });
});
