import { describe, expect, it, vi } from 'vitest';
import { InstitutionalEventBus, MemoryEventPersistence } from '../../event_bus/src/index.js';
import { MINING_PLUGIN_CERTIFICATION_EVENTS, type MiningPluginCertificationEventName } from '../src/events.js';
import { makeAuthority, makeSubmission, pipelineAndCertify, fakeProviders, passingResult } from './testHelpers.js';
describe('IMPCA events, explainability, trust graph, and optional notifier', () => {
  it('publishes all nine certification events under its additive event category', async () => {
    const bus=new InstitutionalEventBus({persistence:new MemoryEventPersistence()}); const authority=makeAuthority({eventBus:bus,providers:fakeProviders({securityValidation:{validate:(input)=>input.pluginUuid === 'plugin-failure' ? passingResult({passed:false,rationale:'intentional event failure'}) : passingResult()}})}); const handlers=Object.fromEntries(Object.values(MINING_PLUGIN_CERTIFICATION_EVENTS).map((name)=>[name,vi.fn()])); for (const [name,handler] of Object.entries(handlers)) authority.events.subscribe(name as MiningPluginCertificationEventName,handler as () => void);
    const first=authority.submit(makeSubmission()); await authority.runPipeline(first.certificationId,makeSubmission().manifest); await authority.certify(first.certificationId); authority.suspend(first.certificationId,'review'); authority.revoke(first.certificationId,'confirmed issue'); await authority.recertify(first.certificationId,makeSubmission().manifest);
    const failed=authority.submit(makeSubmission({pluginUuid:'plugin-failure'})); await authority.runPipeline(failed.certificationId,makeSubmission().manifest);
    await new Promise((resolve)=>setTimeout(resolve,0)); for (const handler of Object.values(handlers)) expect(handler).toHaveBeenCalled(); expect(bus.getEventDefinitions('mining-plugin-certification').map((definition)=>definition.name)).toEqual(expect.arrayContaining(Object.values(MINING_PLUGIN_CERTIFICATION_EVENTS)));
  });
  it('explains pipeline evidence and exposes the complete institutional plugin trust lineage', async () => { const {authority,submitted}=await pipelineAndCertify(); const explanation=authority.explain(submitted.certificationId); expect(explanation).toMatchObject({plugin:{pluginUuid:'plugin-001'},certification:{stage:'Active',level:'Production'}}); expect(explanation.evidenceEvaluated).toHaveLength(7); expect(explanation.testsFailed).toEqual([]); const kinds=authority.trustGraph.chain(submitted.certificationId).map((node)=>node.kind); expect(kinds).toEqual(expect.arrayContaining(['plugin','version','certification','dependency','adapter','algorithm','hardware','runtime','historical-performance','security-evidence'])); });
  it('works with no notifier and sends a certification-only handoff when optional notifier is supplied', async () => { await expect(pipelineAndCertify()).resolves.toBeDefined(); const notifyCertification=vi.fn(); const authority=makeAuthority({capabilityRegistrationNotifier:{notifyCertification}}); const submitted=authority.submit(makeSubmission()); await authority.runPipeline(submitted.certificationId,makeSubmission().manifest); await authority.certify(submitted.certificationId); expect(notifyCertification).toHaveBeenCalledWith(expect.objectContaining({pluginUuid:'plugin-001',status:expect.objectContaining({certified:true})})); });
});
