import { describe, expect, it } from 'vitest';
import { assignCertificationLevel } from '../src/levelAssignment.js';
import { CertificationLevel, type EvidenceRecord, type PipelineStageResult } from '../src/types.js';
import { makeAuthority, makeSubmission, fakeProviders, passingResult } from './testHelpers.js';
const names: PipelineStageResult['stage'][]=['StaticValidation','DependencyValidation','SecurityValidation','FunctionalTesting','CompatibilityTesting','PerformanceTesting','RuntimeTesting'];
function material(score: number, options: { degraded?: boolean; critical?: boolean; failPerformance?: boolean } = {}) { const results=names.map((stage,index)=>({stage,passed:!(options.failPerformance && stage==='PerformanceTesting'),evidenceReference:`e-${index}`,rationale:'test',degraded:options.degraded===true})); const evidence=results.map((result,index)=>({evidenceId:result.evidenceReference,pluginUuid:'p',version:'v',certificationId:'c',stage:result.stage,type:'test',payload:{qualityScore:score,institutionalCritical:options.critical===true},observedAt:'2026-01-01T00:00:00.000Z',providerRationale:'test',passed:result.passed,degraded:result.degraded} satisfies EvidenceRecord)); return {results,evidence}; }
describe('IMPCA deterministic certification levels and immutable evidence', () => {
  it.each([[50,{},CertificationLevel.Experimental],[60,{},CertificationLevel.Development],[75,{},CertificationLevel.Qualified],[90,{},CertificationLevel.Production],[95,{critical:true},CertificationLevel.InstitutionalCritical]] as const)('assigns %s evidence deterministically to %s', (score, options, expected) => { const {results,evidence}=material(score,options); expect(assignCertificationLevel(results,evidence)).toBe(expected); });
  it('does not permit a performance-testing failure to reach Production', () => { const {results,evidence}=material(100,{failPerformance:true,critical:true}); expect(assignCertificationLevel(results,evidence)).toBeUndefined(); });
  it('caps degraded otherwise-good evidence below Production', () => { const {results,evidence}=material(90,{degraded:true}); expect(assignCertificationLevel(results,evidence)).toBe(CertificationLevel.Qualified); });
  it('deep freezes append-only provider evidence', async () => { const payload={qualityScore:90,nested:{value:'original'}}; const authority=makeAuthority({providers:fakeProviders({staticValidation:{validate:()=>passingResult({payload})}})}); const submitted=authority.submit(makeSubmission()); await authority.runPipeline(submitted.certificationId,makeSubmission().manifest); payload.nested.value='mutated'; const stored=authority.evidence.evidenceFor(submitted.certificationId)[0]!; expect(stored.payload).toMatchObject({nested:{value:'original'}}); expect(Object.isFrozen(stored)).toBe(true); expect(Object.isFrozen(stored.payload)).toBe(true); expect(()=>{ (stored.payload as {qualityScore:number}).qualityScore=0; }).toThrow(); });
});
