import { describe, expect, it } from 'vitest';
import { assertPluginCertificationLifecycleTransition } from '../src/lifecycle.js';
import { PluginCertificationLifecycleError, PluginSelfCertificationError } from '../src/errors.js';
import { CertificationLifecycleStage } from '../src/types.js';
import { makeAuthority, makeSubmission, pipelineAndCertify, fakeProviders, passingResult } from './testHelpers.js';
describe('IMPCA lifecycle and non-bypass trust rules', () => {
  it('enforces full guarded lifecycle, including static rejection and testing failure paths', async () => {
    const success=await pipelineAndCertify(); expect(success.certified.lifecycle.map((entry)=>entry.to)).toEqual([CertificationLifecycleStage.Submitted,CertificationLifecycleStage.Validated,CertificationLifecycleStage.Testing,CertificationLifecycleStage.EvidenceCollected,CertificationLifecycleStage.Reviewed,CertificationLifecycleStage.Certified,CertificationLifecycleStage.Active]);
    const rejected=makeAuthority({providers:fakeProviders({staticValidation:{validate:()=>passingResult({passed:false,rationale:'invalid manifest'})}})}); const submitted=rejected.submit(makeSubmission()); const rejectedRecord=await rejected.runPipeline(submitted.certificationId,makeSubmission().manifest); expect(rejectedRecord.lifecycleStage).toBe(CertificationLifecycleStage.Rejected); expect(rejectedRecord.lifecycle.at(-1)?.from).toBe(CertificationLifecycleStage.Validated);
    const reviewFailure=makeAuthority({providers:fakeProviders({securityValidation:{validate:()=>passingResult({payload:{qualityScore:90,certificationBlocked:true}})}})}); const reviewSubmission=reviewFailure.submit(makeSubmission()); await reviewFailure.runPipeline(reviewSubmission.certificationId,makeSubmission().manifest); expect((await reviewFailure.certify(reviewSubmission.certificationId)).lifecycleStage).toBe(CertificationLifecycleStage.Failed);
    expect(()=>assertPluginCertificationLifecycleTransition(CertificationLifecycleStage.Revoked,CertificationLifecycleStage.Active)).toThrow(PluginCertificationLifecycleError);
  });
  it('refuses self-declared plugin certification rather than trusting manifest claims', () => { const authority=makeAuthority(); expect(()=>authority.submit(makeSubmission({manifest:{...makeSubmission().manifest!,selfDeclaredCertificationLevel:'InstitutionalCritical'}}))).toThrow(PluginSelfCertificationError); });
  it('reports no evidence as not certified and cannot certify without a pipeline evidence trail', async () => { const authority=makeAuthority(); const submitted=authority.submit(makeSubmission()); expect(authority.getCertificationStatus({pluginUuid:'plugin-001',version:'1.0.0'})).toEqual({certified:false,level:'None',reason:'Certification is currently Submitted.'}); await expect(authority.certify(submitted.certificationId)).rejects.toThrow('EvidenceCollected'); });
  it('never exposes a successful-loading signal as a trust input or public API', () => { const methods=Object.getOwnPropertyNames(makeAuthority().__proto__); expect(methods).not.toEqual(expect.arrayContaining(['load','recordSuccessfulLoad','acceptRuntimeSuccess','markLoaded'])); });
  it('keeps revoked status uncertified until full provider-backed recertification completes', async () => { const {authority,submitted}=await pipelineAndCertify(); authority.revoke(submitted.certificationId,'security regression'); expect(authority.getCertificationStatus({pluginUuid:'plugin-001',version:'1.0.0'})).toMatchObject({certified:false}); expect(()=>assertPluginCertificationLifecycleTransition(CertificationLifecycleStage.Revoked,CertificationLifecycleStage.Active)).toThrow(); const recertified=await authority.recertify(submitted.certificationId,makeSubmission().manifest); expect(recertified.lifecycleStage).toBe(CertificationLifecycleStage.Active); expect(authority.getCertificationStatus({pluginUuid:'plugin-001',version:'1.0.0'})).toMatchObject({certified:true}); });
});
