import { MiningPluginCertificationAuthority } from '../src/MiningPluginCertificationAuthority.js';
import type { MiningPluginCertificationAuthorityDependencies, PluginCertificationPipelineProviders } from '../src/providers.js';
import type { PipelineProviderResult, PluginCertificationManifest, PluginCertificationSubmission } from '../src/types.js';

export function makeClock(start = '2026-08-09T14:00:00.000Z') { let time=Date.parse(start); return { now: () => new Date(time).toISOString(), advance: (milliseconds: number) => { time += milliseconds; } }; }
export function passingResult(overrides: Partial<PipelineProviderResult> = {}): PipelineProviderResult { return { passed:true, evidenceType:'impca-test-evidence', payload:{ qualityScore:90, dependencies:['dependency-a'], adapters:['adapter-a'], algorithms:['sha256'], hardware:['hardware-a'], runtime:['bounded-runtime'], historicalPerformance:['benchmark-a'], securityEvidence:['security-scan-a'] }, rationale:'Injected IMPCA provider passed.', ...overrides }; }
export function fakeProviders(overrides: Partial<PluginCertificationPipelineProviders> = {}): PluginCertificationPipelineProviders { return { staticValidation:{validate:()=>passingResult({evidenceType:'static'})}, dependencyValidation:{validate:()=>passingResult({evidenceType:'dependency'})}, securityValidation:{validate:()=>passingResult({evidenceType:'security'})}, functionalTesting:{test:()=>passingResult({evidenceType:'functional'})}, compatibilityTesting:{test:()=>passingResult({evidenceType:'compatibility'})}, performanceTesting:{test:()=>passingResult({evidenceType:'performance'})}, runtimeTesting:{test:()=>passingResult({evidenceType:'runtime'})}, ...overrides }; }
export function makeManifest(overrides: Partial<PluginCertificationManifest> = {}): PluginCertificationManifest { return { pluginUuid:'plugin-001', version:'1.0.0', declaredDependencies:[], declaredCapabilities:['mining'], requiredInterfaces:[], ...overrides }; }
export function makeSubmission(overrides: Partial<PluginCertificationSubmission> = {}): PluginCertificationSubmission { return { pluginUuid:'plugin-001', version:'1.0.0', manifest:makeManifest(), ...overrides }; }
export function makeAuthority(options: Partial<MiningPluginCertificationAuthorityDependencies> = {}) { const clock=options.clock ?? makeClock(); let counter=0; return new MiningPluginCertificationAuthority({ providers:options.providers ?? fakeProviders(), clock, createUuid:options.createUuid ?? (() => `fixed-${++counter}`), eventBus:options.eventBus, capabilityRegistrationNotifier:options.capabilityRegistrationNotifier }); }
export async function pipelineAndCertify(authority = makeAuthority(), submission = makeSubmission()) { const submitted=authority.submit(submission); await authority.runPipeline(submitted.certificationId, submission.manifest); const certified=await authority.certify(submitted.certificationId); return { authority, submitted, certified }; }
