import { describe, expect, it } from 'vitest';
import { NormalizedErrorCategory } from '../../mining_adapter_framework/src/types.js';
import { GPU_MINING_EVENTS } from '../src/events.js';
import { detectGpuFailureConditions } from '../src/failureHandling.js';
import { config, FakeGpuAdapter, makeFramework } from './testHelpers.js';
describe('IGMF GPU failure detection, events, and explainability', () => {
  it('detects all eight named failure conditions and uses normalized IMAF categories where applicable', () => { const { framework } = makeFramework(); const profile = framework.composeGpuProfile('gpu-nvidia'); profile.powerState.budgetExceeded = true; profile.thermalState.state = 'critical'; const errors = [
    { category: NormalizedErrorCategory.DriverFailure, message: 'driver failure', retriable: false }, { category: NormalizedErrorCategory.HardwareIncompatible, message: 'GPU absent', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'CUDA out of memory', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'VRAM out of memory', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'thermal throttling', retriable: false }, { category: NormalizedErrorCategory.RuntimeFailure, message: 'power.limit violation', retriable: false }, { category: NormalizedErrorCategory.ProcessFailure, message: 'miner crash', retriable: false }, { category: NormalizedErrorCategory.PoolFailure, message: 'pool failed', retriable: false },
  ];
    const found = new Set(errors.flatMap((error, index) => detectGpuFailureConditions({ profile, requiredVramMB: index === 3 ? 9000 : 2048, adapterHealth: { status: index === 6 ? 'faulted' : 'healthy', reasons: index === 7 ? ['pool offline'] : [] }, adapterError: error, gpuPresent: index !== 1, at: 't' }).map((condition) => condition.type)));
    expect(found).toEqual(new Set(['driver-failure', 'gpu-disappearance', 'cuda-opencl-error', 'vram-exhaustion', 'thermal-throttling', 'power-limit-violation', 'miner-crash', 'pool-failure'])); });
  it('publishes all ten named events and explains lifecycle compatibility isolation and failures', async () => { const { framework, providers } = makeFramework(); providers.thermal.getThermalState = () => ({ currentCelsius: 95, state: 'critical', sensorAvailable: true }); providers.power.getPowerState = () => ({ currentWatts: 300, budgetExceeded: true, state: 'degraded', sensorAvailable: true }); const received: string[] = []; for (const event of Object.values(GPU_MINING_EVENTS)) framework.subscribe(event, () => received.push(event)); const adapter = new FakeGpuAdapter(); const session = await framework.start(config(adapter)); const monitored = await framework.monitor(session.sessionId, { category: NormalizedErrorCategory.PoolFailure, message: 'pool failed', retriable: true }); await framework.stop(session.sessionId); const broken = new FakeGpuAdapter(); broken.failStart = true; await expect(framework.start(config(broken, 'gpu-amd'))).rejects.toThrow('fixture start failure'); expect(new Set(received)).toEqual(new Set(Object.values(GPU_MINING_EVENTS))); expect(framework.explainLifecycle(session.sessionId).stage).toBe('stopped'); expect(framework.explainCompatibility(session.sessionId).compatible).toBe(true); expect(framework.explainIsolation().isolated).toBe(true); expect(framework.explainFailures(session.sessionId, monitored.failures).degraded).toBe(true); });
});
