import { describe, expect, it } from 'vitest';
import { negotiateGpuCapability } from '../src/capabilityNegotiation.js';
import { composeGpuProfile } from '../src/gpuProfile.js';
import { GpuIdentityRegistry } from '../src/multiGpu.js';
import { VramManagement } from '../src/vramManagement.js';
import { GpuMiningValidationError } from '../src/errors.js';
import { config, FakeGpuAdapter, FakeGpuProviders, TEST_ALGORITHM } from './testHelpers.js';
describe('IGMF composed GPU profile, UUID identity, and VRAM pre-validation', () => {
  it('composes a fresh source-owned profile without cache', () => { const p = new FakeGpuProviders(); const first = composeGpuProfile(p, 'gpu-nvidia'); p.thermal.getThermalState = () => ({ currentCelsius: 81, state: 'warning', sensorAvailable: true }); const second = composeGpuProfile(p, 'gpu-nvidia'); expect(first).toMatchObject({ gpuUuid: 'gpu-nvidia', vendor: 'NVIDIA', vramTotalMB: 8192, vramAvailableMB: 7168, thermalState: { hotspotCelsius: 75 }, certificationStatus: { status: 'certified' } }); expect(second.thermalState.currentCelsius).toBe(81); expect(first.thermalState.currentCelsius).toBe(65); });
  it('keeps multiple vendors independently UUID-addressable with no primary ordering assumption', () => { const p = new FakeGpuProviders(); const registry = new GpuIdentityRegistry(p.hardware); expect(registry.list()).toEqual(['gpu-amd', 'gpu-intel', 'gpu-nvidia']); expect(registry.require('gpu-amd').vendor).toBe('AMD'); expect(registry.require('gpu-intel').vendor).toBe('Intel'); expect(registry.require('gpu-nvidia').vendor).toBe('NVIDIA'); });
  it('rejects insufficient VRAM before calling IRIA and is deterministic', () => { const p = new FakeGpuProviders(); const manager = new VramManagement(p.resource); const profile = composeGpuProfile(p, 'gpu-nvidia'); const a = manager.prevalidate(profile, 9000); const b = manager.prevalidate(profile, 9000); expect(a).toEqual(b); expect(a.valid).toBe(false); expect(() => manager.reserve(profile, { gpuUuid: 'gpu-nvidia', requiredVramMB: 9000, requestedComputeQueues: 1, owner: 'x', requestingAuthority: 'x' })).toThrow(GpuMiningValidationError); expect(p.calls.reserve).toBe(0); expect(manager.reserve(profile, { gpuUuid: 'gpu-nvidia', requiredVramMB: 2048, requestedComputeQueues: 1, owner: 'x', requestingAuthority: 'x' }).grantedVramMB).toBe(2048); });
  it('negotiates GPU compatibility deterministically for compatible and incompatible inputs', async () => { const p = new FakeGpuProviders(); const adapter = new FakeGpuAdapter(); const manifest = await adapter.identify(); const good = negotiateGpuCapability({ profile: composeGpuProfile(p, 'gpu-nvidia'), config: config(adapter), manifest, requiredVramMB: 2048, supportedVendors: ['NVIDIA'], supportedArchitectures: ['Ada'], minimumDriverVersion: '500', minimumComputeCapability: '8.0' }); const bad = negotiateGpuCapability({ profile: composeGpuProfile(p, 'gpu-nvidia'), config: { ...config(adapter), algorithm: 'unsupported' }, manifest, requiredVramMB: 9000, supportedVendors: ['AMD'] }); expect(good).toEqual(negotiateGpuCapability({ profile: composeGpuProfile(p, 'gpu-nvidia'), config: config(adapter), manifest, requiredVramMB: 2048, supportedVendors: ['NVIDIA'], supportedArchitectures: ['Ada'], minimumDriverVersion: '500', minimumComputeCapability: '8.0' })); expect(good.compatible).toBe(true); expect(bad.compatible).toBe(false); expect(bad.reasons.join(' ')).toContain('Available VRAM'); expect(TEST_ALGORITHM).toBe('test-gpu-algo-fixture'); });
});
