import type { MiningAdapter } from '../../mining_adapter_framework/src/adapterContract.js';
import type { AdapterCapabilities, AdapterDiagnostics, AdapterHealth, AdapterManifest, AdapterPreparationContext, AdapterValidationRequest, AdapterValidationResult, BackendConfig, NormalizedStatistics } from '../../mining_adapter_framework/src/types.js';
import { GpuMiningFramework } from '../src/GpuMiningFramework.js';
import type { GpuMiningConfig } from '../src/types.js';
import type { GpuMiningProviders } from '../src/providers.js';
export const TEST_ALGORITHM = 'test-gpu-algo-fixture';
export class FakeGpuAdapter implements MiningAdapter {
  started = 0; stopped = 0; statisticsValue: unknown = { hashrateHps: 1000, acceptedShares: 10, rejectedShares: 1, errorRate: .01, uptimeSeconds: 120, workerStatus: 'running', temperatureCelsius: 65, powerWatts: 200, extensions: { invalidShares: 0 } }; healthValue: AdapterHealth = { status: 'healthy', reasons: [] }; failStart = false;
  async identify(): Promise<AdapterManifest> { return { adapterId: 'fake-gpu-adapter', name: 'Fake GPU Adapter', version: '1', vendor: 'test', backend: 'fixture', supportedOperatingSystems: ['test'], supportedHardware: ['gpu'], supportedAlgorithms: [TEST_ALGORITHM], supportedProtocols: ['test-pool'], requiredCapabilities: [], supportedFeatures: [], configurationSchema: {}, minimumFrameworkVersion: '1', certificationStatus: 'development' }; }
  async validate(_r: AdapterValidationRequest): Promise<AdapterValidationResult> { return { valid: true, reasons: [] }; } async configure(_c: BackendConfig): Promise<void> {} async prepare(_c: AdapterPreparationContext): Promise<void> {} async start(): Promise<void> { this.started++; if (this.failStart) throw new Error('fixture start failure'); } async pause(): Promise<void> {} async resume(): Promise<void> {} async stop(): Promise<void> { this.stopped++; } async restart(): Promise<void> {} async health(): Promise<AdapterHealth> { return this.healthValue; } async statistics(): Promise<unknown> { return this.statisticsValue; } async capabilities(): Promise<AdapterCapabilities> { return { operatingSystems: ['test'], hardware: ['gpu'], algorithms: [TEST_ALGORITHM], protocols: ['test-pool'], statistics: ['hashrateHps'], controlOperations: ['start', 'stop'], features: [] }; } async diagnostics(): Promise<AdapterDiagnostics> { return { details: {} }; } async cleanup(): Promise<void> {}
}
export class FakeGpuProviders implements GpuMiningProviders {
  calls = { reserve: 0, release: 0, mutation: 0 }; ids = ['gpu-nvidia', 'gpu-amd', 'gpu-intel']; allocations: Record<string, { totalVramMB: number; usedVramMB: number; availableVramMB: number; allocatedComputeQueues: number; availableComputeQueues: number; contentionReasons?: string[] }> = {};
  constructor() { for (const id of this.ids) this.allocations[id] = { totalVramMB: 8192, usedVramMB: 1024, availableVramMB: 7168, allocatedComputeQueues: 0, availableComputeQueues: 1, contentionReasons: [] }; }
  hardware = { listGpus: () => [...this.ids], getGpu: (id: string) => ({ gpuUuid: id, vendor: id.includes('amd') ? 'AMD' : id.includes('intel') ? 'Intel' : 'NVIDIA', model: id, architecture: id.includes('amd') ? 'RDNA' : id.includes('intel') ? 'Xe' : 'Ada', vramTotalMB: this.allocations[id]?.totalVramMB ?? 0, driverVersion: '550.1', computeCapability: '8.9', pcie: { bus: id, generation: '4', lanes: 16 }, health: 'healthy' as const, healthReasons: [], availableAlgorithms: [TEST_ALGORITHM] }) };
  resource = { reserveVram: (request: { gpuUuid: string; requiredVramMB: number; requestedComputeQueues: number }) => { this.calls.reserve++; return { reservationId: `reservation-${this.calls.reserve}`, gpuUuid: request.gpuUuid, grantedVramMB: request.requiredVramMB, grantedComputeQueues: request.requestedComputeQueues }; }, releaseVram: (_id: string, _reason: string) => { this.calls.release++; }, getAllocation: (id: string) => ({ ...this.allocations[id] }) };
  thermal = { getThermalState: (_id: string) => ({ currentCelsius: 65, hotspotCelsius: 75, memoryCelsius: 70, fanRpm: 1200, state: 'nominal' as const, warningThresholdCelsius: 80, criticalThresholdCelsius: 90, sensorAvailable: true }) };
  power = { getPowerState: (_id: string) => ({ currentWatts: 200, maximumRatedWatts: 300, powerLimitWatts: 250, budgetExceeded: false, state: 'healthy' as const, fanStatus: 'available' as const, sensorAvailable: true }) };
  certification = { getCertificationStatus: (_id: string) => ({ status: 'certified' as const, certificationId: 'cert-gpu' }) };
}
export function config(adapter: MiningAdapter, gpuUuid = 'gpu-nvidia', overrides: Partial<GpuMiningConfig> = {}): GpuMiningConfig { return { gpuUuid, algorithm: TEST_ALGORITHM, pool: { endpoint: 'test://pool', protocol: 'test-pool' }, walletReference: 'opaque-wallet-reference', workerIdentity: `worker-${gpuUuid}`, intensity: 5, memoryConfiguration: { requiredVramMB: 2048 }, backendAdapter: adapter, powerPolicyReference: 'opaque-power-policy', performancePolicyReference: 'opaque-performance-policy', ...overrides }; }
export function makeFramework(providers = new FakeGpuProviders()) { const framework = new GpuMiningFramework({ providers, now: () => '2026-08-09T14:00:00.000Z' }); return { framework, providers }; }
export function normalized(overrides: Partial<NormalizedStatistics> = {}): NormalizedStatistics { return { hashrateHps: 1000, acceptedShares: 10, rejectedShares: 1, errorRate: .01, uptimeSeconds: 120, workerStatus: 'running', temperatureCelsius: 65, powerWatts: 200, extensions: { invalidShares: 0 }, ...overrides }; }
